package dao;

import entity.Wallet;
import entity.WalletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int countByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int deleteByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    List<Wallet> selectByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    Wallet selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Wallet record, @Param("example") WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int updateByExample(@Param("record") Wallet record, @Param("example") WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Jul 12 19:43:49 CST 2018
     */
    int updateByPrimaryKey(Wallet record);
}